server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: crm-service
          uri: lb://crm-service
          predicates:
            - Path=/crm/**
          filters:
            - StripPrefix=1
        - id: logistic-service
          uri: lb://logistic-service
          predicates:
            - Path=/logistics/**
          filters:
            - StripPrefix=1
        - id: warehouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/warehouse/**
          filters:
            - StripPrefix=1
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1

