server:
  port: 8200

spring:
  application:
    name: warehouse-service

  profiles:
    active: default

  cloud:
    nacos:
      server-addr: localhost:8848
      # 注册中心
      discovery:
        server-addr: localhost:8848
        ephemeral: false
      # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml

  datasource:
    url: jdbc:mysql://localhost:3306/warehouse?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: CHqh5489!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
