server:
  port: 8000

spring:
  application:
    name: crm-service

  profiles:
    active: default

  cloud:
    nacos:
      server-addr: localhost:8848
      # 注册中心
      discovery:
        server-addr: localhost:8848
        ephemeral: false
      # 配置中心
      config:
        server-addr: localhost:8848
        file-extension: yaml

  sleuth:
    sampler:
      probability: 1.0

  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 10
    instances:
      logistic-service:
        baseConfig: default
      warehouse-service:
        baseConfig: default
      payment-service:
        baseConfig: default

